var users = require('./users.server.model'),
    answers = require('./answers.server.model'),
    questions = require('./questions.server.model'),
    leftswipe = require('./leftswipe.server.model'),
    rightswipe = require('./rightswipe.server.model'),
    match = require('./match.server.model'),
    category = require('./category.server.model'),
    eventlocation = require('./eventlocation.server.model'),
    events = require('./events.server.modal'),
    eventattend = require('./eventattend.server.model'),
    eventinterest = require('./eventinterest.server.model'),
    privacy = require('./privacy.server.model'),
    terms = require('./terms.server.model'),
    promotions = require('./promotions.server.model'),
    currentsubscription = require('./currentsub.server.model'),
    subscription = require('./subscription.server.model'),
    feedback= require('./feedback.server.model'),
    models = {
        users,
        answers,
        questions,
        leftswipe,
        rightswipe,
        match,
        category,
        eventlocation,
        events,
        eventattend,
        eventinterest,
        privacy,
        terms,
        promotions,
        subscription,
        feedback,
        currentsubscription
    }
module.exports = models;